package com.dragsville.scan2excel.data.local

import androidx.room.RoomDatabaseConstructor

actual object ScanDatabaseConstructor : RoomDatabaseConstructor<ScanDatabase> {
    actual override fun initialize(): ScanDatabase = throw NotImplementedError("Generated by Room")
}